language: node_js
node_js: 8

os:
  - osx
  - linux

cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar
      - gcc-multilib
      - g++-multilib

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - npm install -g xvfb-maybe
  - yarn

script:
  - yarn run build

notifications:
  slack: ramme:44ubE4BVf3FGi8OldEKL743J
  email: false
